logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/E85Addict/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = true
build-mode = "both"
patches-source = "revanced/revanced-patches"
cli-source = "revanced/revanced-cli"
module-prop-name = "youtube-SWZ"
# patcher-args = "-e 'Change header' -Oheader='premium*header' -e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true "
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true "
excluded-patches = "'Enable debugging' 'Custom branding'"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music]
enabled = false
build-mode = "both"
patches-source = "revanced/revanced-patches"
cli-source = "revanced/revanced-cli"
module-prop-name = "music-SWZ"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[GooglePhotos]
enabled = true
build-mode = "both"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Spotify]
enabled = false
version = "auto"
archive-dlurl = "https://archive.org/download/e85-apks/apks/com.spotify.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
included-patches = "'Change version code'"

[Prime-Video]
enabled = true
app-name = "PrimeVideo"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
included-patches = "'Rename shared permissions' 'Change version code'"
