enable-magisk-update = true
logging-to-file = true
parallel-jobs = 1

[YouTube]
enabled = false
app-name = "YouTube"
module-prop-name = "youtube-rod"
patches-source = "revanced/revanced-patches"
cli-source = "revanced/revanced-cli"
version = "auto"
build-mode = "both"
excluded-patches = "'Enable debugging' 'Custom branding'"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
enabled = false
app-name = "Music"
module-prop-name = "music-rod"
patches-source = "revanced/revanced-patches"
cli-source = "revanced/revanced-cli"
version = "auto"
build-mode = "both"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Anddea]
enabled = true
app-name = "YouTube"
module-prop-name = "youtube-rod"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
version = "auto"
build-mode = "both"
included-patches = "'Theme' 'Hide shortcuts'"
patcher-args = "--legacy-options options.json"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Anddea]
enabled = false
app-name = "Music"
module-prop-name = "music-rod"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
included-patches = "'Dark theme'"
patcher-args = "--legacy-options options.json"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
module-prop-name = "youtube-rod"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
version = "auto"
build-mode = "both"
excluded-patches = "'Custom branding'"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Morphe]
enabled = false
app-name = "Music"
module-prop-name = "music-rod"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
excluded-patches = "'Custom branding'"
build-mode = "both"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Instagram]
enabled = true
app-name = "Instagram"
patches-source = "revanced/revanced-patches"
cli-source = "revanced/revanced-cli"
rv-brand = "ReVanced"
version = "auto"
build-mode = "apk"
included-patches = "'Anonymous story viewing' 'Disable Reels scrolling' 'Disable signature check' 'Disable story auto flipping' 'Enable developer menu' 'Hide ads' 'Hide explore feed' 'Hide suggested content' 'Limit feed to followed profiles' 'Open links externally' 'Remove build expired popup' 'Sanitize sharing links'"
arch = "arm64-v8a"
dpi = "nodpi anydpi 120-640dpi"
include-stock = false
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.instagram.android"

[GooglePhotos]
enabled = true
build-mode = "both"
version = "auto"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Spotify]
enabled = false
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
version = "auto"
included-patches = "'Custom theme'"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"

[Prime-Video]
enabled = false
app-name = "PrimeVideo"
version = "auto"
included-patches = "'Rename shared permissions' 'Change version code'"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video"
uptodown-dlurl = "https://amazon-video.uptodown.com/android"

[Strava]
enabled = false
app-name = "Strava"
version = "auto"
included-patches = "'Change version code'"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true
uptodown-dlurl = "https://strava.uptodown.com/android"

[Disney-Plus]
enabled = false
app-name = "DisneyPlus"
version = "auto"
included-patches = "'Change version code'"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/disney/disney"
uptodown-dlurl = "https://disney-disneyplus.uptodown.com/android"
