enable-magisk-update = true
logging-to-file = true
parallel-jobs = 1

[YouTube]
enabled = false
build-mode = "both"
module-prop-name = "youtube-rod"
patches-source = "revanced/revanced-patches"
cli-source = "revanced/revanced-cli"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true"
excluded-patches = "'Enable debugging' 'Custom branding'"
version = "auto"
arch = "arm64-v8a"
dpi = "nodpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music]
enabled = false
build-mode = "both"
module-prop-name = "music-rod"
patches-source = "revanced/revanced-patches"
cli-source = "revanced/revanced-cli"
version = "auto"
arch = "arm64-v8a"
dpi = "nodpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[YouTube-Anddea]
enabled = true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
module-prop-name = "youtube-rod"
included-patches = "'Theme' 'Hide shortcuts'"
patcher-args = "--legacy-options options.json"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true

[Music-Anddea]
enabled = false
app-name = "Music"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
module-prop-name = "music-rod"
included-patches = "'Dark theme'"
patcher-args = "--legacy-options options.json"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
excluded-patches = "'Custom branding'"
build-mode = "both"
module-prop-name = "youtube-rod"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true

[Music-Morphe]
enabled = false
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
excluded-patches = "'Custom branding'"
build-mode = "both"
module-prop-name = "music-rod"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
dpi = "nodpi"
include-stock = false
riplib = true

[GooglePhotos]
enabled = true
build-mode = "both"
version = "auto"
arch = "arm64-v8a"
dpi = "nodpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Spotify]
enabled = false
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
version = "auto"
included-patches = "'Custom theme'"
archive-dlurl = "https://archive.org/download/e85-apks/apks/com.spotify.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
arch = "arm64-v8a"
dpi = "nodpi"

[Prime-Video]
enabled = false
app-name = "PrimeVideo"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video"
uptodown-dlurl = "https://amazon-video.uptodown.com/android"
included-patches = "'Rename shared permissions' 'Change version code'"
arch = "arm64-v8a"
dpi = "nodpi"

[Strava]
enabled = false
app-name = "Strava"
version = "auto"
uptodown-dlurl = "https://strava.uptodown.com/android"
included-patches = "'Change version code'"
arch = "arm64-v8a"
dpi = "nodpi"

[Disney-Plus]
enabled = false
app-name = "DisneyPlus"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/disney/disney"
uptodown-dlurl = "https://disney-disneyplus.uptodown.com/android"
included-patches = "'Change version code'"
arch = "arm64-v8a"
dpi = "nodpi"
